version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - app-network
  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4:6.21
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "root"
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network